/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fucfuc_testJNIapi */

#ifndef _Included_com_example_fucfuc_testJNIapi
#define _Included_com_example_fucfuc_testJNIapi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fucfuc_testJNIapi
 * Method:    SynthesisVideo
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_fucfuc_testJNIapi_SynthesisVideo(
		JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_fucfuc_testJNIapi
 * Method:    ReplaceAudio
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_fucfuc_testJNIapi_ReplaceAudio(JNIEnv *,
		jclass, jstring,jstring);


JNIEXPORT jint JNICALL Java_com_example_fucfuc_testJNIapi_cropVideo(JNIEnv *,
		jclass, jstring,jstring);

#ifdef __cplusplus
}
#endif
#endif
